// <auto-generated />
using System;
using EPB11.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPB11.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230608045231_InitialDatabaseSetup")]
    partial class InitialDatabaseSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EPB11.Models.AchizitieModel", b =>
                {
                    b.Property<int>("AchizitieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchizitieId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfflineOnline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PretPerUnitate")
                        .HasColumnType("int");

                    b.Property<int>("PretTotal")
                        .HasColumnType("int");

                    b.Property<int>("SumaTotalaAchizitii")
                        .HasColumnType("int");

                    b.Property<int>("Unitate")
                        .HasColumnType("int");

                    b.HasKey("AchizitieId");

                    b.ToTable("Achizitie");
                });

            modelBuilder.Entity("EPB11.Models.ObiectivModel", b =>
                {
                    b.Property<int>("ObiectivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObiectivId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfflineOnline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PretPerUnitate")
                        .HasColumnType("int");

                    b.Property<int>("SoldId")
                        .HasColumnType("int");

                    b.Property<int>("SumaDeStrans")
                        .HasColumnType("int");

                    b.Property<string>("SumaPerTimp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SumaTotala")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimpRamas")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unitate")
                        .HasColumnType("int");

                    b.HasKey("ObiectivId");

                    b.HasIndex("SoldId");

                    b.ToTable("Obiectiv");
                });

            modelBuilder.Entity("EPB11.Models.SoldModel", b =>
                {
                    b.Property<int>("SoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoldId"));

                    b.Property<int>("AchizitieId")
                        .HasColumnType("int");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<int>("VenitId")
                        .HasColumnType("int");

                    b.HasKey("SoldId");

                    b.HasIndex("AchizitieId");

                    b.HasIndex("VenitId");

                    b.ToTable("Sold");
                });

            modelBuilder.Entity("EPB11.Models.VenitModel", b =>
                {
                    b.Property<int>("VenitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenitId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Suma")
                        .HasColumnType("int");

                    b.Property<int>("SumaTotalaVenituri")
                        .HasColumnType("int");

                    b.Property<string>("Sursa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenitId");

                    b.ToTable("Venit");
                });

            modelBuilder.Entity("EPB11.Models.ObiectivModel", b =>
                {
                    b.HasOne("EPB11.Models.SoldModel", "sold")
                        .WithMany()
                        .HasForeignKey("SoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sold");
                });

            modelBuilder.Entity("EPB11.Models.SoldModel", b =>
                {
                    b.HasOne("EPB11.Models.AchizitieModel", "achizitie")
                        .WithMany()
                        .HasForeignKey("AchizitieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EPB11.Models.VenitModel", "venit")
                        .WithMany()
                        .HasForeignKey("VenitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("achizitie");

                    b.Navigation("venit");
                });
#pragma warning restore 612, 618
        }
    }
}
